import type { PortfolioConcentrationEngine } from "@/src/lib/portfolio/concentration/concentration-engine";
import type {
  PortfolioConcentrationInput,
  PortfolioConcentrationItem,
  PortfolioConcentrationLevel,
  PortfolioConcentrationReport,
} from "@/src/lib/portfolio/concentration/concentration-types";
import type { PortfolioExposureItem } from "@/src/lib/portfolio/exposure/exposure-types";

const GENERATED_AT = "2026-06-11T00:00:00.000Z";

function concentrationLevelFromPercentage(percentage: number): PortfolioConcentrationLevel {
  if (percentage >= 50) {
    return "CRITICAL";
  }

  if (percentage >= 35) {
    return "HIGH";
  }

  if (percentage >= 20) {
    return "MEDIUM";
  }

  return "LOW";
}

function levelScore(level: PortfolioConcentrationLevel) {
  return {
    CRITICAL: 4,
    HIGH: 3,
    LOW: 1,
    MEDIUM: 2,
  }[level];
}

function highestLevel(levels: PortfolioConcentrationLevel[]) {
  return levels.reduce<PortfolioConcentrationLevel>(
    (highest, level) => (levelScore(level) > levelScore(highest) ? level : highest),
    "LOW",
  );
}

function topItem(items: PortfolioExposureItem[]) {
  return [...items].sort(
    (left, right) => right.percentage - left.percentage || left.label.localeCompare(right.label),
  )[0];
}

function toConcentrationItem(item: PortfolioExposureItem | undefined) {
  if (!item) {
    return null;
  }

  return {
    category: item.category,
    key: item.key,
    label: item.label,
    level: concentrationLevelFromPercentage(item.percentage),
    marketValue: item.marketValue,
    percentage: item.percentage,
  } satisfies PortfolioConcentrationItem;
}

function buildAlerts(items: Array<PortfolioConcentrationItem | null>) {
  return items
    .filter((item): item is PortfolioConcentrationItem => Boolean(item))
    .filter((item) => item.level === "HIGH" || item.level === "CRITICAL")
    .map(
      (item) =>
        `${item.label} concentration is ${item.level.toLowerCase()} at ${item.percentage.toFixed(
          1,
        )}%.`,
    );
}

function buildSummary(input: {
  alerts: string[];
  overallConcentration: PortfolioConcentrationLevel;
  topSymbol: PortfolioConcentrationItem | null;
}) {
  if (!input.topSymbol) {
    return "Portfolio Concentration Engine is enabled, but no concentration data is available yet.";
  }

  if (input.alerts.length > 0) {
    return `Overall concentration is ${input.overallConcentration}. Largest symbol exposure is ${input.topSymbol.label} at ${input.topSymbol.percentage.toFixed(
      1,
    )}%. Monitoring and risk-awareness only.`;
  }

  return `Overall concentration is ${input.overallConcentration}. No high concentration alert is currently generated by the mock engine. Monitoring and risk-awareness only.`;
}

export const mockPortfolioConcentrationEngine: PortfolioConcentrationEngine = {
  async generateConcentration(
    input: PortfolioConcentrationInput,
  ): Promise<PortfolioConcentrationReport> {
    const topSymbol = toConcentrationItem(topItem(input.exposureReport.symbolExposure));
    const topFcnUnderlying = toConcentrationItem(
      topItem(
        input.exposureReport.symbolExposure.filter(
          (item) => item.category === "fcn_underlying",
        ),
      ),
    );
    const topAssetType = toConcentrationItem(topItem(input.exposureReport.assetTypeExposure));
    const topProvider = toConcentrationItem(topItem(input.exposureReport.providerExposure));
    const topRegion = toConcentrationItem(topItem(input.exposureReport.regionExposure));
    const concentrationItems = [
      topSymbol,
      topFcnUnderlying,
      topAssetType,
      topProvider,
      topRegion,
    ];
    const levels = concentrationItems
      .filter((item): item is PortfolioConcentrationItem => Boolean(item))
      .map((item) => item.level);
    const concentrationScore = Math.min(
      100,
      Math.round(
        Math.max(
          0,
          ...concentrationItems.map((item) => item?.percentage ?? 0),
        ),
      ),
    );
    const overallConcentration = levels.length > 0 ? highestLevel(levels) : "LOW";
    const alerts = buildAlerts(concentrationItems);

    return {
      alerts,
      concentrationScore,
      generatedAt: GENERATED_AT,
      id: "mock-portfolio-concentration-report-v2-06",
      overallConcentration,
      summary: buildSummary({
        alerts,
        overallConcentration,
        topSymbol,
      }),
      topAssetType,
      topFcnUnderlying,
      topProvider,
      topRegion,
      topSymbol,
    };
  },
};
