import type { RawEditorialProviderItem } from "@/src/lib/editorial/editorial-types";

export function getDailyBrief2MockSourceItems(): RawEditorialProviderItem[] {
  return [
    {
      categories: ["macro"],
      confidence: 0.88,
      description:
        "Fed rate expectations and inflation data remain the main macro driver for global risk appetite.",
      headline: "Rates remain the anchor for global market tone",
      id: "mock-macro-rates",
      importance: 0.88,
      markets: ["global", "us"],
      providerKey: "ixai-mock-editorial",
      publishedAt: "2026-07-06T00:30:00.000Z",
      sourceId: "mock-global-macro",
      sourceKind: "manual",
      sourceLabel: "IXAI Mock Macro Desk",
      symbols: ["SPX", "TLT", "DXY"],
    },
    {
      categories: ["us_equity"],
      confidence: 0.86,
      description:
        "Large-cap AI and semiconductor names continue to define the direction of US equity sentiment.",
      headline: "US AI leaders keep market breadth in focus",
      id: "mock-us-ai-equity",
      importance: 0.84,
      markets: ["us"],
      providerKey: "ixai-mock-editorial",
      publishedAt: "2026-07-06T01:05:00.000Z",
      sourceId: "mock-us-equities",
      sourceKind: "manual",
      sourceLabel: "IXAI Mock US Equity Desk",
      symbols: ["NVDA", "MSFT", "TSLA"],
    },
    {
      categories: ["taiwan_market"],
      confidence: 0.82,
      description:
        "Taiwan AI supply-chain positioning remains tied to global semiconductor demand and US tech sentiment.",
      headline: "Taiwan AI supply chain tracks global semiconductor momentum",
      id: "mock-taiwan-ai-chain",
      importance: 0.78,
      markets: ["tw", "us"],
      providerKey: "ixai-mock-editorial",
      publishedAt: "2026-07-06T01:20:00.000Z",
      sourceId: "mock-taiwan-market",
      sourceKind: "manual",
      sourceLabel: "IXAI Mock Taiwan Desk",
      symbols: ["TSM", "2330"],
    },
    {
      categories: ["crypto"],
      confidence: 0.8,
      description:
        "Bitcoin and Ether volatility remains elevated as liquidity and macro expectations shift intraday.",
      headline: "Crypto volatility stays elevated around BTC and ETH",
      id: "mock-crypto-volatility",
      importance: 0.72,
      markets: ["crypto", "global"],
      providerKey: "ixai-mock-editorial",
      publishedAt: "2026-07-06T01:45:00.000Z",
      sourceId: "mock-crypto-market",
      sourceKind: "manual",
      sourceLabel: "IXAI Mock Crypto Desk",
      symbols: ["BTC", "ETH"],
    },
    {
      categories: ["fcn_structured_products"],
      confidence: 0.76,
      description:
        "Structured-product monitoring should watch worst-of underlyings, observation calendars, and volatility conditions.",
      headline: "FCN monitoring focus stays on worst-of underlyings and observation timing",
      id: "mock-fcn-monitoring",
      importance: 0.74,
      markets: ["global", "us", "hk"],
      providerKey: "ixai-mock-editorial",
      publishedAt: "2026-07-06T02:05:00.000Z",
      sourceId: "mock-fcn-structured",
      sourceKind: "manual",
      sourceLabel: "IXAI Mock FCN Desk",
      symbols: ["NVDA", "TSLA", "0700.HK"],
    },
    {
      categories: ["risk_volatility"],
      confidence: 0.7,
      description:
        "Cross-asset volatility is the main uncertainty variable for today's public market read.",
      headline: "Volatility remains the key uncertainty marker",
      id: "mock-risk-volatility",
      importance: 0.7,
      markets: ["global"],
      providerKey: "ixai-mock-editorial",
      publishedAt: "2026-07-06T02:20:00.000Z",
      sourceId: "mock-risk-desk",
      sourceKind: "manual",
      sourceLabel: "IXAI Mock Risk Desk",
      symbols: ["VIX"],
    },
    {
      categories: ["risk_volatility"],
      confidence: 0.68,
      description:
        "Cross-asset volatility is the main uncertainty variable for today's public market read.",
      headline: "Volatility remains the key uncertainty marker",
      id: "mock-risk-volatility-duplicate",
      importance: 0.68,
      markets: ["global"],
      providerKey: "ixai-mock-editorial",
      publishedAt: "2026-07-06T02:25:00.000Z",
      sourceId: "mock-risk-desk",
      sourceKind: "manual",
      sourceLabel: "IXAI Mock Risk Desk",
      symbols: ["VIX"],
    },
  ];
}
